/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      "colors": {
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "surface-tint": "#565e74",
        "tertiary-fixed-dim": "#c6c6c7",
        "outline": "#76777d",
        "secondary-fixed-dim": "#eec200",
        "surface-container-highest": "#d3e4fe",
        "on-surface": "#0b1c30",
        "primary-container": "#131b2e",
        "surface-container-high": "#dce9ff",
        "on-primary-fixed-variant": "#3f465c",
        "on-secondary-fixed": "#231b00",
        "on-primary-fixed": "#131b2e",
        "tertiary-fixed": "#e2e2e2",
        "surface": "#f8f9ff",
        "surface-container": "#e5eeff",
        "on-secondary-container": "#6f5900",
        "outline-variant": "#c6c6cd",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#cbdbf5",
        "secondary-container": "#fed01b",
        "secondary-fixed": "#ffe083",
        "on-tertiary-fixed-variant": "#454747",
        "on-tertiary-fixed": "#1a1c1c",
        "tertiary-container": "#1a1c1c",
        "primary-fixed": "#dae2fd",
        "on-primary-container": "#7c839b",
        "primary": "#000000",
        "on-tertiary-container": "#838484",
        "error-container": "#ffdad6",
        "background": "#f8f9ff",
        "secondary": "#735c00",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "on-surface-variant": "#45464d",
        "surface-bright": "#f8f9ff",
        "on-secondary-fixed-variant": "#574500",
        "inverse-surface": "#213145",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#bec6e0",
        "on-error-container": "#93000a",
        "on-background": "#0b1c30",
        "inverse-primary": "#bec6e0",
        "tertiary": "#000000",
        "surface-variant": "#d3e4fe",
        "surface-container-low": "#eff4ff",
        "on-secondary": "#ffffff",
        "fithae-pink": "#E91E63",
        "fithae-yellow": "#FFEB3B"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "xs": "4px",
        "gutter": "24px",
        "sm": "8px",
        "xxl": "64px",
        "container-max": "1280px",
        "unit": "4px",
        "md": "16px",
        "lg": "24px",
        "xl": "40px",
        "margin-mobile": "16px"
      },
      "fontFamily": {
        "headline-lg": ["Playfair Display"],
        "body-sm": ["Inter"],
        "label-bold": ["Inter"],
        "display-lg-mobile": ["Playfair Display"],
        "body-lg": ["Inter"],
        "display-lg": ["Playfair Display"],
        "body-md": ["Inter"],
        "label-caps": ["Inter"],
        "headline-md": ["Playfair Display"]
      }
    },
  },
  plugins: [],
}
